### ISSUE TITLE
Starting Place Icon

### ISSUE THREAD

**Issue by SkOODaT** [kylepaulsen/ValheimWebMap#4]
the starting icon is map center but my starting place is not there, can we get admin command to move it~

**Comment by kylepaulsen** [comment]
Thanks for reporting. I should have guessed that the starting area is not guaranteed to be at 0,0 .

**Comment by SkOODaT** [comment]
1 of my worlds it lined up but another is WAY off and the 3rd a tiny bit lol

**Comment by kylepaulsen** [comment]
Hopefully this should be fixed now. v1.0.3 .
Make sure to clear browser cache, as frontend code is aggressively cached.

**Comment by uilson** [comment]
this is unimplemented, it doesn't get the value from anywhere, so it  always returns {0,0,0} because of the "vector3.zero"

**Comment by uilson** [comment]
this is still not working, it doesn't seem to get the value, so it always returns {0,0,0} because of the "vector3.zero" i believe

edit: some how it works some times.. not sure whats going on
